### ISSUE TITLE
.scss files won't import images as background

### ISSUE THREAD

**Issue by dutraneto** [marceloglacial/snowflake-boilerplate#43]
I have tried different paths for importing an image as a background, but webpack has always compiling with errors

![code](https://user-images.githubusercontent.com/18724070/108252249-6f9a2100-7126-11eb-807e-e5d3b6892b00.png)

**Comment by dutraneto** [comment]
![code](https://user-images.githubusercontent.com/18724070/109042040-b6939380-769d-11eb-8527-3e1ca29fdb86.png)

I have figure this out using these settings in Webpack 

<img width="861" alt="Screen Shot 2021-02-24 at 12 43 36 PM" src="https://user-images.githubusercontent.com/18724070/109042253-f9556b80-769d-11eb-9afe-1a4612a3294c.png">

**Comment by dutraneto** [comment]
Vou abrir um PR mais tarde

**Comment by marceloglacial** [comment]
Solved. Thank you. https://github.com/marceloglacial/snowflake-boilerplate/pull/45
