### ISSUE TITLE
Missing 2k (QHD, 1440p) resolution on media query variables

### ISSUE THREAD

**Issue by dutraneto** [marceloglacial/snowflake-boilerplate#44]
There would be good to have a 2560px resolution for supporting 1440p monitors on media-query variables like so:

![code1](https://user-images.githubusercontent.com/18724070/108614076-78f4e900-73c5-11eb-8fca-d0ff64f93add.png)

I tried to implement a feature and noticed that media-query has not been setting such:

![code](https://user-images.githubusercontent.com/18724070/108614088-a2ae1000-73c5-11eb-928d-2b808d52d340.png)

**Comment by marceloglacial** [comment]
Solved. Thank you. https://github.com/marceloglacial/snowflake-boilerplate/pull/46
